require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe QuizRunsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # QuizRun. As you add validations to QuizRun, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuizRunsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all quiz_runs as @quiz_runs" do
      quiz_run = QuizRun.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:quiz_runs)).to eq([quiz_run])
    end
  end

  describe "GET show" do
    it "assigns the requested quiz_run as @quiz_run" do
      quiz_run = QuizRun.create! valid_attributes
      get :show, {:id => quiz_run.to_param}, valid_session
      expect(assigns(:quiz_run)).to eq(quiz_run)
    end
  end

  describe "GET new" do
    it "assigns a new quiz_run as @quiz_run" do
      get :new, {}, valid_session
      expect(assigns(:quiz_run)).to be_a_new(QuizRun)
    end
  end

  describe "GET edit" do
    it "assigns the requested quiz_run as @quiz_run" do
      quiz_run = QuizRun.create! valid_attributes
      get :edit, {:id => quiz_run.to_param}, valid_session
      expect(assigns(:quiz_run)).to eq(quiz_run)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuizRun" do
        expect {
          post :create, {:quiz_run => valid_attributes}, valid_session
        }.to change(QuizRun, :count).by(1)
      end

      it "assigns a newly created quiz_run as @quiz_run" do
        post :create, {:quiz_run => valid_attributes}, valid_session
        expect(assigns(:quiz_run)).to be_a(QuizRun)
        expect(assigns(:quiz_run)).to be_persisted
      end

      it "redirects to the created quiz_run" do
        post :create, {:quiz_run => valid_attributes}, valid_session
        expect(response).to redirect_to(QuizRun.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quiz_run as @quiz_run" do
        post :create, {:quiz_run => invalid_attributes}, valid_session
        expect(assigns(:quiz_run)).to be_a_new(QuizRun)
      end

      it "re-renders the 'new' template" do
        post :create, {:quiz_run => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quiz_run" do
        quiz_run = QuizRun.create! valid_attributes
        put :update, {:id => quiz_run.to_param, :quiz_run => new_attributes}, valid_session
        quiz_run.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested quiz_run as @quiz_run" do
        quiz_run = QuizRun.create! valid_attributes
        put :update, {:id => quiz_run.to_param, :quiz_run => valid_attributes}, valid_session
        expect(assigns(:quiz_run)).to eq(quiz_run)
      end

      it "redirects to the quiz_run" do
        quiz_run = QuizRun.create! valid_attributes
        put :update, {:id => quiz_run.to_param, :quiz_run => valid_attributes}, valid_session
        expect(response).to redirect_to(quiz_run)
      end
    end

    describe "with invalid params" do
      it "assigns the quiz_run as @quiz_run" do
        quiz_run = QuizRun.create! valid_attributes
        put :update, {:id => quiz_run.to_param, :quiz_run => invalid_attributes}, valid_session
        expect(assigns(:quiz_run)).to eq(quiz_run)
      end

      it "re-renders the 'edit' template" do
        quiz_run = QuizRun.create! valid_attributes
        put :update, {:id => quiz_run.to_param, :quiz_run => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quiz_run" do
      quiz_run = QuizRun.create! valid_attributes
      expect {
        delete :destroy, {:id => quiz_run.to_param}, valid_session
      }.to change(QuizRun, :count).by(-1)
    end

    it "redirects to the quiz_runs list" do
      quiz_run = QuizRun.create! valid_attributes
      delete :destroy, {:id => quiz_run.to_param}, valid_session
      expect(response).to redirect_to(quiz_runs_url)
    end
  end

end
